#!/usr/bin/env python3
"""
provenance.py — project book-level provenance into the ontology graph.

Reads:
  * content/books.json      — the book registry + inter-book `requires` graph
  * ontology/entities.jsonl — entity index carrying attestedIn / definedIn
                              (populated by tools/build.py)

Writes a regenerable block at the END of ontology/world.ttl:
  * a small provenance vocabulary (amol:Sourcebook / amol:attestedIn /
    amol:definedIn / amol:bookSlug)
  * one amol:Sourcebook node per book, with dc:title, amol:bookSlug and a
    dc:requires edge to each book it depends on ("additional spells" -> core rules)
  * per-entity amol:attestedIn (books that mention it) and amol:definedIn
    (book it was extracted from) edges

This makes the provenance the build derives (entities.jsonl) queryable as
first-class edges in the RDF graph, so a consumer can reconstruct "the world as
known from book subset S" (optionally closed under dc:requires) via SPARQL.

Idempotent: re-running replaces its own block, never the curated spine or the
tools/ttl_from_entities.py extracted-entities block.

ORDER: run AFTER tools/ttl_from_entities.py (which truncates everything after its
own marker) and AFTER tools/build.py (which fills attestedIn/definedIn). Canonical
pipeline: extract -> ttl_from_entities -> build -> provenance.

Run with rdflib available (host or the tools Docker image).
"""
import argparse, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "# ============ BEGIN PROVENANCE (generated by tools/provenance.py) ============"
AMOL = "https://ontorag.dev/amol/"


def book_local(slug):
    """Deterministic Turtle local name for a book slug (shared by nodes + edges)."""
    parts = re.split(r"[^A-Za-z0-9]+", slug)
    return "Book_" + "".join(p[:1].upper() + p[1:] for p in parts if p)


def esc(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


def entity_local(iri):
    return iri[len(AMOL):] if iri.startswith(AMOL) else None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--books", default=os.path.join(ROOT, "content", "books.json"))
    ap.add_argument("--entities", default=os.path.join(ROOT, "ontology", "entities.jsonl"))
    ap.add_argument("--ttl", default=os.path.join(ROOT, "ontology", "world.ttl"))
    args = ap.parse_args()

    books = json.load(open(args.books, encoding="utf-8"))
    known = set(books)

    # --- book nodes + dc:requires graph ---
    book_lines = []
    for slug, meta in books.items():
        loc = book_local(slug)
        line = ["amol:%s a amol:Sourcebook, schema:Book ;" % loc,
                "    dc:title %s ;" % esc(meta.get("title") or slug),
                "    amol:bookSlug %s" % esc(slug)]
        reqs = [r for r in meta.get("requires", []) if r in known]
        if reqs:
            line[-1] += " ;"
            line.append("    dc:requires %s ." % ", ".join("amol:%s" % book_local(r) for r in reqs))
        else:
            line[-1] += " ."
        book_lines.append("\n".join(line))

    # --- per-entity provenance edges ---
    ent_lines, n_ent = [], 0
    for raw in open(args.entities, encoding="utf-8"):
        raw = raw.strip()
        if not raw:
            continue
        e = json.loads(raw)
        att = [s for s in e.get("attestedIn", []) if s in known]
        dfn = [s for s in e.get("definedIn", []) if s in known]
        if not att and not dfn:
            continue
        loc = entity_local(e["iri"])
        if not loc:
            continue
        preds = []
        if att:
            preds.append("amol:attestedIn %s" % ", ".join("amol:%s" % book_local(s) for s in att))
        if dfn:
            preds.append("amol:definedIn %s" % ", ".join("amol:%s" % book_local(s) for s in dfn))
        ent_lines.append("amol:%s %s ." % (loc, " ;\n    ".join(preds)))
        n_ent += 1

    # --- assemble block ---
    vocab = "\n".join([
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "",
        "amol:Sourcebook a rdfs:Class ; rdfs:label \"Sourcebook\" ;",
        "    rdfs:comment \"A published book that contributes entities and edges to the world graph.\" .",
        "amol:attestedIn a rdf:Property ; rdfs:label \"attested in\" ;",
        "    rdfs:comment \"Links an entity to a Sourcebook whose prose mentions it.\" .",
        "amol:definedIn a rdf:Property ; rdfs:label \"defined in\" ;",
        "    rdfs:comment \"Links an entity to the Sourcebook it was extracted/defined from.\" .",
        "amol:bookSlug a rdf:Property ; rdfs:label \"book slug\" .",
    ])

    spine = open(args.ttl, encoding="utf-8").read()
    if MARKER in spine:
        spine = spine.split(MARKER)[0].rstrip() + "\n"

    out = [spine.rstrip(), "", MARKER, "", vocab, "",
           "# %d books and their dc:requires dependency graph" % len(books), ""]
    out += book_lines
    out += ["", "# provenance edges for %d entities (amol:attestedIn / amol:definedIn)" % n_ent, ""]
    out += ent_lines
    with open(args.ttl, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    # validate the whole graph still parses
    from rdflib import Graph
    Graph().parse(args.ttl, format="turtle")
    print("wrote %s" % args.ttl)
    print("  %d book nodes (+requires graph); %d entities with provenance edges"
          % (len(books), n_ent))


if __name__ == "__main__":
    main()
