#!/usr/bin/env python3
"""
provenance.py — project book-level provenance into the ontology graph, using the
OntoRAG Provenance and Citation Ontology (orp:, https://ontorag.org/provenance#).

Reads:
  * content/books.json      — the book registry + inter-book `requires` graph
  * content/sources.json    — per-book source file (path, sha256)
  * ontology/entities.jsonl — entity index carrying attestedIn / definedIn
                              (populated by tools/build.py)

Writes a regenerable block at the END of ontology/world.ttl:
  * one orp:Source per book (dcterms:title, dcterms:identifier = slug, and a
    dcterms:requires edge to each book it depends on)
  * one orp:SourceFile per book (orp:fileOf, orp:checksum "sha256:<hex>")
  * one orp:Pack per book (orp:packOf, orp:namedGraph, orp:requires mirroring the
    book DAG) plus the orp:SpinePack holding the shared vocabulary
  * per-entity orp:attestedIn (books that mention it) and orp:definedIn (book it
    was extracted from) edges to the orp:Source nodes

This makes the provenance the build derives (entities.jsonl) queryable as
first-class edges in the RDF graph, so a consumer can select the packs it holds and
reconstruct "the world as known from those books". The selection rules (access
scope vs. composition) are at https://ontorag.org/provenance/#packs.

Idempotent: re-running replaces its own block, never the curated spine or the
tools/ttl_from_entities.py extracted-entities block.

ORDER: run AFTER tools/ttl_from_entities.py (which truncates everything after its
own marker) and AFTER tools/build.py (which fills attestedIn/definedIn). Canonical
pipeline: extract -> ttl_from_entities -> build -> provenance.

Run with rdflib available (host or the tools Docker image).
"""
import argparse, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "# ============ BEGIN PROVENANCE (generated by tools/provenance.py) ============"
AMOL = "https://www.fantasymaps.org/amol-ontorag/id/"
SPINE = "spine"


def source_iri(slug):
    return "<%ssource/%s>" % (AMOL, slug)


def pack_iri(slug):
    return "<%spack/%s>" % (AMOL, slug)


def graph_iri(slug):
    return "<%sgraph/%s>" % (AMOL, slug)


def file_iri(sha256):
    return "<%sfile/sha256-%s>" % (AMOL, sha256)


def esc(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


def entity_local(iri):
    return iri[len(AMOL):] if iri.startswith(AMOL) else None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--books", default=os.path.join(ROOT, "content", "books.json"))
    ap.add_argument("--sources", default=os.path.join(ROOT, "content", "sources.json"))
    ap.add_argument("--entities", default=os.path.join(ROOT, "ontology", "entities.jsonl"))
    ap.add_argument("--ttl", default=os.path.join(ROOT, "ontology", "world.ttl"))
    args = ap.parse_args()

    books = json.load(open(args.books, encoding="utf-8"))
    sources = json.load(open(args.sources, encoding="utf-8")) if os.path.exists(args.sources) else {}
    known = set(books)

    # --- sources, files and packs ---
    book_lines = []
    for slug, meta in books.items():
        reqs = [r for r in meta.get("requires", []) if r in known]
        src = [
            "%s a orp:Source ;" % source_iri(slug),
            "    dc:title %s ;" % esc(meta.get("title") or slug),
            "    dc:identifier %s" % esc(slug),
        ]
        if reqs:
            src[-1] += " ;"
            src.append("    dc:requires %s" % ", ".join(source_iri(r) for r in reqs))
        src[-1] += " ."
        book_lines.append("\n".join(src))

        sha = (sources.get(slug) or {}).get("sha256")
        if sha:
            book_lines.append("\n".join([
                "%s a orp:SourceFile ;" % file_iri(sha),
                "    orp:fileOf %s ;" % source_iri(slug),
                "    orp:checksum %s ;" % esc("sha256:" + sha),
                '    dc:format "text/markdown" .',
            ]))

        pack = [
            "%s a orp:Pack ;" % pack_iri(slug),
            "    orp:packOf %s ;" % source_iri(slug),
            "    orp:namedGraph %s" % graph_iri(slug),
        ]
        if reqs:
            pack[-1] += " ;"
            pack.append("    orp:requires %s" % ", ".join(pack_iri(r) for r in reqs))
        pack[-1] += " ."
        book_lines.append("\n".join(pack))

    spine = "\n".join([
        "%s a orp:SpinePack ;" % pack_iri(SPINE),
        '    dc:title "Ars Magica shared vocabulary" ;',
        '    dc:description "Curated world, rule set, Arts and grouping tags: entities with no definedIn, in scope for every composition." ;',
        "    orp:namedGraph %s ." % graph_iri(SPINE),
    ])

    # --- per-entity provenance edges ---
    ent_lines, n_ent = [], 0
    for raw in open(args.entities, encoding="utf-8"):
        raw = raw.strip()
        if not raw:
            continue
        e = json.loads(raw)
        att = [s for s in e.get("attestedIn", []) if s in known]
        dfn = [s for s in e.get("definedIn", []) if s in known]
        if not att and not dfn:
            continue
        loc = entity_local(e["iri"])
        if not loc:
            continue
        preds = []
        if att:
            preds.append("orp:attestedIn %s" % ", ".join(source_iri(s) for s in att))
        if dfn:
            preds.append("orp:definedIn %s" % ", ".join(source_iri(s) for s in dfn))
        ent_lines.append("amol:%s %s ." % (loc, " ;\n    ".join(preds)))
        n_ent += 1

    # --- assemble block ---
    header = "\n".join([
        "@prefix orp: <https://ontorag.org/provenance#> .",
        "",
        "# Sources, files and packs follow the OntoRAG Provenance and Citation Ontology:",
        "# https://ontorag.org/provenance/ . Pack named-graph IRIs say where each pack's",
        "# statements belong when the graph is loaded per pack; this file is the union.",
    ])

    spine_ttl = open(args.ttl, encoding="utf-8").read()
    if MARKER in spine_ttl:
        spine_ttl = spine_ttl.split(MARKER)[0].rstrip() + "\n"

    out = [spine_ttl.rstrip(), "", MARKER, "", header, "",
           "# %d books: orp:Source + orp:SourceFile + orp:Pack each, and the spine pack" % len(books), ""]
    out += book_lines
    out += ["", spine, "",
            "# provenance edges for %d entities (orp:attestedIn / orp:definedIn)" % n_ent, ""]
    out += ent_lines
    with open(args.ttl, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    # validate the whole graph still parses
    from rdflib import Graph
    Graph().parse(args.ttl, format="turtle")
    print("wrote %s" % args.ttl)
    print("  %d books (source + file + pack) + spine pack; %d entities with provenance edges"
          % (len(books), n_ent))


if __name__ == "__main__":
    main()
