#!/usr/bin/env python3
"""
ttl_from_entities.py — merge Claude-extracted entities (shard files) into the
ontology graph (ontology/world.ttl).

Reads the JSON-array shards written by the extraction workflow, dedupes by
normalized name, maps each extracted `type` onto an rpg-schema class + grouping
tag, mints IRIs, and APPENDS them to the curated spine of world.ttl inside a
regenerable block (curated entities win over extracted duplicates).

Idempotent: re-running replaces the generated block, never the curated spine.
Run with rdflib available (host or the tools Docker image).
"""
import argparse, glob, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "# ============ BEGIN EXTRACTED ENTITIES (generated by ttl_from_entities.py) ============"

# type -> (rpg class, grouping tag IRI, inWorld?, definedInRuleSet predicate or None)
TYPE_MAP = {
    "Character":     ("rpg:Character",  "amol:CharacterTag",   True,  None),
    "House":         ("rpg:Faction",    "amol:HermeticHouse",  True,  None),
    "Tribunal":      ("rpg:Faction",    "amol:Tribunal",       True,  None),
    "Covenant":      ("rpg:Faction",    "amol:Covenant",       True,  None),
    "Faction":       ("rpg:Faction",    "amol:FactionTag",     True,  None),
    "Spell":         ("rpg:Spell",      "amol:NamedSpell",     False, "rpg:capabilityDefinedInRuleSet"),
    "Item":          ("rpg:Item",       "amol:MagicItem",      False, "rpg:itemDefinedInRuleSet"),
    "Creature":      ("rpg:Creature",   "amol:Creature",       True,  None),
    "Virtue":        ("rpg:Tag",        "amol:Virtue",         False, None),
    "Flaw":          ("rpg:Tag",        "amol:Flaw",           False, None),
    "Ability":       ("rpg:Proficiency","amol:HermeticAbility",False, "rpg:capabilityDefinedInRuleSet"),
    "Art":           ("rpg:Proficiency","amol:HermeticArt",    False, "rpg:capabilityDefinedInRuleSet"),
    "Concept":       ("rpg:Tag",        "amol:HermeticConcept",False, None),
    "Realm":         ("rpg:Tag",        "amol:Realm",          False, None),
    "Place":         ("schema:Place",   "amol:Place",          True,  None),
    "CharacterType": ("rpg:Tag",        "amol:CharacterType",  False, None),
}
TAG_LABELS = {
    "amol:CharacterTag": "Character", "amol:HermeticHouse": "Hermetic House",
    "amol:Tribunal": "Tribunal", "amol:Covenant": "Covenant", "amol:FactionTag": "Faction",
    "amol:NamedSpell": "Named Spell", "amol:MagicItem": "Magic Item", "amol:Creature": "Creature",
    "amol:Virtue": "Virtue", "amol:Flaw": "Flaw", "amol:HermeticAbility": "Hermetic Ability",
    "amol:HermeticArt": "Hermetic Art", "amol:HermeticConcept": "Hermetic Concept",
    "amol:Realm": "Realm of Power", "amol:CharacterType": "Character Type", "amol:Place": "Place",
}
AMOL = "https://ontorag.dev/amol/"


def norm(s):
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9 ]", "", re.sub(r"^the\s+", "", s.lower()))).strip()

def mint(name, used):
    parts = re.findall(r"[A-Za-z0-9]+", name)
    local = "".join(p[:1].upper() + p[1:] for p in parts) or "Entity"
    if local[0].isdigit():
        local = "E" + local
    local = local[:60]
    base, i = local, 2
    while local in used:
        local = "%s_%d" % (base, i); i += 1
    used.add(local)
    return local

def ttl_str(s):
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", " ")
    return '"%s"' % re.sub(r"\s+", " ", s).strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--shards", default=os.path.join(ROOT, "ontology", "_extract", "desc"))
    ap.add_argument("--base", default=os.path.join(ROOT, "ontology", "world.ttl"))
    ap.add_argument("--out", default=os.path.join(ROOT, "ontology", "world.ttl"))
    ap.add_argument("--max-aliases", type=int, default=8)
    args = ap.parse_args()

    from rdflib import Graph, RDF, RDFS, Namespace
    from rdflib.namespace import SKOS

    # --- curated spine (truncate any previously-generated block) ---
    spine = open(args.base, encoding="utf-8").read()
    if MARKER in spine:
        spine = spine.split(MARKER)[0].rstrip() + "\n"

    g = Graph(); g.parse(data=spine, format="turtle")
    RPG = Namespace("https://rpg-schema.org/ns/rpg#")
    SCHEMA = Namespace("https://schema.org/")
    taken_names, taken_locals, taken_tag_iris = set(), set(), set()
    for s in set(g.subjects()):
        ss = str(s)
        if not ss.startswith(AMOL):
            continue
        taken_locals.add(ss[len(AMOL):])
        taken_tag_iris.add(ss)
        for p in (RPG.name, SCHEMA.name, RDFS.label, SKOS.prefLabel, SKOS.altLabel):
            for o in g.objects(s, p):
                taken_names.add(norm(str(o)))

    # --- load + dedupe extracted shards ---
    raw = []
    for f in sorted(glob.glob(os.path.join(args.shards, "*.json"))):
        try:
            data = json.load(open(f, encoding="utf-8"))
            raw.extend(data if isinstance(data, list) else data.get("entities", []))
        except Exception as e:
            print("  WARN: could not parse %s (%s)" % (os.path.basename(f), e))
    seen, ents = set(), []
    for e in raw:
        name = (e.get("name") or "").strip()
        if not name or not re.search(r"[A-Za-z]", name):
            continue
        k = norm(name)
        if len(k) < 2 or k in seen or k in taken_names:
            continue
        seen.add(k)
        ents.append(e)

    # --- emit ---
    used_locals = set(taken_locals)
    needed_tags = {}
    blocks = []
    by_class = {}
    for e in ents:
        name = e["name"].strip()
        typ = e.get("type", "Concept")
        cls, tag, in_world, defined = TYPE_MAP.get(typ, TYPE_MAP["Concept"])
        local = mint(name, used_locals)
        iri = "amol:" + local
        label_prop = "skos:prefLabel" if cls == "rpg:Tag" else "rpg:name"
        if tag not in taken_tag_iris:
            needed_tags[tag] = TAG_LABELS.get(tag, tag.split(":")[-1])
        lines = ["%s a %s ;" % (iri, cls), "    %s %s ;" % (label_prop, ttl_str(name))]
        desc = (e.get("description") or "").strip()
        if desc:
            lines.append("    dc:description %s ;" % ttl_str(desc))
        aliases = []
        for a in (e.get("aliases") or []):
            a = (a or "").strip()
            if a and norm(a) != norm(name) and a not in aliases:
                aliases.append(a)
        if aliases:
            lines.append("    skos:altLabel %s ;" % ", ".join(ttl_str(a) for a in aliases[:args.max_aliases]))
        if in_world:
            lines.append("    rpg:inWorld amol:MythicEurope ;")
        if defined:
            lines.append("    %s amol:ArM5 ;" % defined)
        lines.append("    rpg:hasTag %s ." % tag)
        blocks.append("\n".join(lines))
        by_class[typ] = by_class.get(typ, 0) + 1

    tag_defs = "\n".join(
        '%s a rpg:Tag ; skos:prefLabel %s .' % (t, ttl_str(lbl))
        for t, lbl in sorted(needed_tags.items())
    )

    out = [spine.rstrip(), "", MARKER, ""]
    if tag_defs:
        out += ["# new grouping tags", tag_defs, ""]
    out += ["# %d extracted entities" % len(ents), ""]
    out += blocks
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    # validate the result parses
    Graph().parse(args.out, format="turtle")
    print("wrote %s" % args.out)
    print("  curated spine kept; %d extracted entities added; %d new grouping tags" % (len(ents), len(needed_tags)))
    print("  by type:", dict(sorted(by_class.items(), key=lambda x: -x[1])))


if __name__ == "__main__":
    main()
